alias v="mvim"
alias v.="v ."
alias vz="v ~/.oh-my-zsh/"
alias vrc="v ~/.zshrc"
alias vzrc="v ~/.oh-my-zsh/ ~/.zshrc"
alias vv="v ~/.{,g}vimrc.local"
alias vvv="v ~/.{,g}vimrc{,.local}"
alias vsnip="v ~/.vim/snippets/"
